### PR TITLE
India indepention hevants

### PR DESCRIPTION
**Pull request by Mr-Jangoon**

### CODE REVIEW

**Comment by Mr-Jangoon** [comment]
pretty sure for all of these conflicting files we can use the ones on mine, because i just merged all of these on my own branch already have done

**Comment by raxo2222** [comment]
Yeah its just couple of changes

**Comment by Mr-Jangoon** [comment]
hope this works :')

**Review by JackEPepper — CHANGES_REQUESTED** [review]
See discord thread for more complete breakdown, current problems I see:

Error Spam when JE is open

Missing LOC/Modifiers

Broken events spam

Less verbose events, keep the options to strictly prose

**Review by JackEPepper — APPROVED** [review]

**Review by DZappala — APPROVED** [review]

**Pull request merged**
